### ISSUE TITLE
java.lang.NullPointerException while accessing Hadoop configuration when reading the state as batch query

### ISSUE THREAD

**Issue by redsk** [HeartSaVioR/spark-state-tool#32]
Hi @HeartSaVioR ,

I'm trying to read the state using the batch query, as in 

```scala
val operatorId = 0
val batchId = 1 // the version of state for the output of batch is batchId + 1

// Here we assume 'spark' as SparkSession
val stateReadDf = spark.read
  .format("state")
  .schema(stateSchema)
  .option(StateStoreDataSourceProvider.PARAM_CHECKPOINT_LOCATION,
    new Path(checkpointRoot, "state").getAbsolutePath)
  .option(StateStoreDataSourceProvider.PARAM_VERSION, batchId + 1)
  .option(StateStoreDataSourceProvider.PARAM_OPERATOR_ID, operatorId)
  .load()
```

If run this query on a Driver only in standalone mode (or in the unittests) all works perfectly. However, if I use a real cluster with executors, I get a NullPointerException:
```
java.lang.NullPointerException
  org.apache.spark.sql.execution.streaming.CheckpointFileManager$.create(CheckpointFileManager.scala:178)
  org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.fm$lzycompute(HDFSBackedStateStoreProvider.scala:265)
  org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.org$apache$spark$sql$execution$streaming$state$HDFSBackedStateStoreProvider$$fm(HDFSBackedStateStoreProvider.scala:265)
  org.apache.spark.sql.execution.streaming.state.HDFSBackedStateStoreProvider.init(HDFSBackedStateStoreProvider.scala:224)
  org.apache.spark.sql.execution.streaming.state.StateStoreProvider$.createAndInit(StateStore.scala:230)
  org.apache.spark.sql.execution.streaming.state.StateStore$.$anonfun$get$1(StateStore.scala:366)
  scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
  org.apache.spark.sql.execution.streaming.state.StateStore$.get(StateStore.scala:365)
  net.heartsavior.spark.sql.state.StateStoreReaderRDD.compute(StateStoreReaderRDD.scala:67)
  org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
  org.apache.spark.rdd.RDD.iterator(RDD.scala:310)
  org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
...
```

When checking Spark code at `CheckpointFileManager.scala:178` I see:
```scala
val fileManagerClass = hadoopConf.get(
      SQLConf.STREAMING_CHECKPOINT_FILE_MANAGER_CLASS.parent.key)
```

I've also tried with `chermenin/spark-states` (which is actually what I tried first) and it also failed with a similar exception in 

```
java.lang.NullPointerException
	at ru.chermenin.spark.sql.execution.streaming.state.RocksDbStateStoreProvider.init(RocksDbStateStoreProvider.scala:359)
	at org.apache.spark.sql.execution.streaming.state.StateStoreProvider$.createAndInit(StateStore.scala:230)
	at org.apache.spark.sql.execution.streaming.state.StateStore$.$anonfun$get$1(StateStore.scala:366)
	at scala.collection.mutable.HashMap.getOrElseUpdate(HashMap.scala:86)
	at org.apache.spark.sql.execution.streaming.state.StateStore$.get(StateStore.scala:365)
	at net.heartsavior.spark.sql.state.StateStoreReaderRDD.compute(StateStoreReaderRDD.scala:67)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:346)
	...
```

`RocksDbStateStoreProvider.scala:359` also reads the Hadoop Conf:
```scala
this.tempDir = getTempDir(getTempPrefix(hadoopConf.get("spark.app.name")), "")
```

So I think the problem could be in `StateStoreReaderRDD.scala`:
```scala
  // A Hadoop Configuration can be about 10 KB, which is pretty big, so broadcast it
  private val hadoopConfBroadcast = session.sparkContext.broadcast(
    new SerializableConfiguration(session.sessionState.newHadoopConf()))

  override def compute(split: Partition, context: TaskContext): Iterator[(UnsafeRow, UnsafeRow)] = {
    split match {
      case p: StateStorePartition =>
        val stateStoreId = StateStoreId(stateCheckpointRootLocation, operatorId,
          p.partition, storeName)
        val stateStoreProviderId = StateStoreProviderId(stateStoreId, p.queryId)

        val store = StateStore.get(stateStoreProviderId, keySchema, valueSchema,
          indexOrdinal = None, version = batchId, storeConf = storeConf,
          hadoopConf = hadoopConfBroadcast.value.value)

        val iter = store.iterator().map(pair => (pair.key, pair.value))

        // close state store provider after using
        StateStore.unload(stateStoreProviderId)

        iter

      case e => throw new IllegalStateException("Expected StateStorePartition but other type of " +
        s"partition passed - $e")
    }
  }
```

I think that for some reason `hadoopConfBroadcast` contains a null value.
It's a bit hard to debug as the problem does no occur if the code is executed locally in debug mode (say in Intellij) or even in Spark in driver only mode (in the end, it's the same JVM this way so the conf does not need to be broadcasted for real...)

Any idea?

**Comment by redsk** [comment]
Update: I added an assertion
```scala
        assert(hadoopConfBroadcast.value.value != null)
        val store = StateStore.get(stateStoreProviderId, keySchema, valueSchema,
          indexOrdinal = None, version = batchId, storeConf = storeConf,
          hadoopConf = hadoopConfBroadcast.value.value)
```
and the assertion failed. So it really seems that `hadoopConfBroadcast.value.value` is null.
